Repository SmartCity-2022/Service-MainHub, pull requests merged in 2022-06, with the labels that each got.

#21 add test suite and change to the create script
  backend/__tests__/API.js
  backend/package-lock.json
  backend/package.json
  backend/requests.rest
  backend/server.js
  backend/start.js
  database/create.sql
  database/drop.sql
Labels: minor

#22 Backend validation
  backend/__tests__/API.js
  backend/config.js
  backend/constants.js
  backend/package-lock.json
  backend/package.json
  backend/requests.rest
  backend/server.js
  database/drop.sql
Labels: minor

#24 fixed field name in refresh access token payload
  backend/requests.rest
  backend/server.js
Labels: patch

#25 fix to refresh token endpoint & redirect on logout
  backend/requests.rest
  backend/server.js
  frontend/src/components/SideNav.js
Labels: patch

#26 add react cypress example tests
  frontend/cypress.config.js
  frontend/cypress/e2e/auth/auth.cy.js
  frontend/cypress/e2e/auth/login.cy.js
  frontend/cypress/fixtures/example.json
  frontend/cypress/support/commands.js
  frontend/cypress/support/e2e.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Login.js
  frontend/src/components/Register.js
  frontend/src/routes/Auth.js
Labels: patch

#27 final version
  README.md
  backend/__tests__/API.js
  backend/config.js
  backend/requests.rest
  backend/routes/testing.js
  backend/server.js
Labels: major

#28 fix refreshtoken bug
  README.md
  backend/server.js
Labels: patch

#29 preparation for presentation
  backend/server.js
Labels: patch

#31 update to test suite settings
  backend/package.json
Labels: skip-release
